<h1>LISTA DE EXERCÍCIOS</h1>

In [6]:
import math
import numpy as np

<b><p>Exercícios 01 - Você tem uma lista de número: [6,7,4,7,8,4,2,5,7,&#39;hum&#39;, &#39;dois&#39;]. A ideia do exercício é
tirar a média de todos os valores contidos na lista, porém para fazer o cálculo
precisa remover as strings.</p></b>

In [30]:
lista = [6,7,4,7,8,4,2,5,7,'hum', 'dois']

media = sum(lista[0:9]) / len(lista)

print('A média é da lista é = ', media)

A média é da lista é =  4.545454545454546


<b><p>Exercício 02 - Crie um método que receba duas matrizes, some os valores total de cada matriz e
depois multiple o resultado delas e retorne o valor.</p></b>

In [33]:
matriz_1 = np.array([[2,2], 
                     [4,1], 
                     [6,4]])

matriz_2 = np.array([[2,4], 
                     [1,64], 
                     [3,4]])


def recebe_matriz(mat1, mat2):

    soma_matriz_1 = mat1.sum()

    soma_matriz_2 = mat2.sum()

    mult = soma_matriz_1 * soma_matriz_2
                                  
    print('O resultado da multiplicação da Matriz 1 com a Matriz 2 é: ', mult)

recebe_matriz(matriz_1, matriz_2)

O resultado da multiplicação da Matriz 1 com a Matriz 2 é:  1482


<b><p>Exercício 03 - Criar uma matriz nxm (n = 5, m =7)<br>
a. faça a matriz transposta desta matriz</p></b>

In [43]:
matriz_exs_03 = np.random.rand(5,7)
print('Matriz (5,7):\n', matriz_exs_03)

matriz_transposta = matriz_exs_03.T
print('Matriz Transposta:\n', matriz_transposta)

Matriz (5,7):
 [[0.02422609 0.43665484 0.75722482 0.19374723 0.62924155 0.64395359
  0.51805086]
 [0.07848235 0.81246626 0.50943933 0.67638977 0.24946871 0.78106869
  0.70989639]
 [0.94841004 0.5633349  0.78186672 0.29904579 0.84820675 0.22788201
  0.37862301]
 [0.53257679 0.82648742 0.67229581 0.47906446 0.05601989 0.95422277
  0.69057872]
 [0.70717197 0.124048   0.52152261 0.08086296 0.02449086 0.02362847
  0.57886682]]
Matriz Transposta:
 [[0.02422609 0.07848235 0.94841004 0.53257679 0.70717197]
 [0.43665484 0.81246626 0.5633349  0.82648742 0.124048  ]
 [0.75722482 0.50943933 0.78186672 0.67229581 0.52152261]
 [0.19374723 0.67638977 0.29904579 0.47906446 0.08086296]
 [0.62924155 0.24946871 0.84820675 0.05601989 0.02449086]
 [0.64395359 0.78106869 0.22788201 0.95422277 0.02362847]
 [0.51805086 0.70989639 0.37862301 0.69057872 0.57886682]]


<b><p>b. somar toda matrix</p>

In [44]:
soma_total_matriz = matriz_exs_03.sum()
print('Soma total da Matriz: ', soma_total_matriz)

Soma total da Matriz:  17.339517222392452


<b>
    <p>c. somar todas as colunas</p>

In [46]:
soma_colunas_matriz = matriz_exs_03.sum(axis = 0)
print('Soma das colunas:\n', soma_colunas_matriz)

Soma das colunas:
 [2.29086724 2.76299141 3.24234927 1.72911021 1.80742776 2.63075552
 2.87601581]


<b>
    <p>d. somar todas as linhas.</p>

In [47]:
soma_linhas_matriz = matriz_exs_03.sum(axis = 1)
print('Soma das linhas:\n', soma_linhas_matriz)

Soma das linhas:
 [3.20309897 3.8172115  4.04736921 4.21124585 2.06059168]


<b><p>e. retorne o maior valor</p>

In [50]:
maior_valor = matriz_exs_03.max()
print('Maior valor da matriz: ', maior_valor)

Maior valor da matriz:  0.9542227701339999


<b><p>f. retorne o menor valor.</p>

In [51]:
menor_valor = matriz_exs_03.min()
print('Menos valor da matriz: ', menor_valor)

Menos valor da matriz:  0.02362846645073291


<b><p>Exercício 04 - Crie uma matriz nxn (n=5). Agora some essa matriz com a matriz do exercício 3.</p></b>

In [76]:
matriz_exs_04 = np.random.rand(5)

soma = sum(matriz_exs_03) + sum(matriz_exs_04)

print('Soma das Matrizes:\n', soma)

Soma das Matrizes:
 [4.00661642 4.47874059 4.95809845 3.44485938 3.52317694 4.3465047
 4.59176498]


<b><p>Exercício 05 - Crie um array de números que vai de 0 a.</p></b>

In [80]:
array_random = np.arange(0,1001)
print(array_random)

[   0    1    2 ...  998  999 1000]


<b><p>Exercício 06 - Crie uma matriz só de zeros.</p></b>

In [87]:
matriz_zero = np.zeros((2,2))
print(matriz_zero)

[[0. 0.]
 [0. 0.]]
